# Generated by Django 5.1.6 on 2025-02-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0002_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummyname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
